In [2]:
import numpy

In [3]:
import pandas
import cv2

In [6]:
im_g=cv2.imread("smallgray.png",0) ## 0 means grey and 1 means BGR Blue,Green,Red

In [48]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [49]:
type(im_g)

numpy.ndarray

In [33]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [11]:
cv2.imwrite("newimagegray.png",im_g)

True

In [13]:
for i in im_g:
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [14]:
for i in im_g.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [15]:
for i in im_g.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [28]:
ims=numpy.hstack((im_g,im_g))

In [45]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [37]:
ims1=numpy.vstack((im_g,im_g))
print(ims1)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [43]:
split1=numpy.vsplit(ims1,2)
split1

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [44]:
split1[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [46]:
split=numpy.hsplit(ims,5)
split

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [47]:
split[1]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)